name: Flutter continous build

on: 
  pull_request:
    branches: [master]

jobs:
  increment_build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.$2.$3.($4+1)/e' test.txt
      - uses: stefanzweifel/git-auto-commit-action@v4.1.6
          with:
            commit_message: build number incremented
            branch: ${{ github.head_ref }}