name: Flutter continous build

on: 
  pull_request:
    branches: [master]

jobs:
  increment_build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.$2.$3.($4+1)/e' test.txt
      - run: git add . 
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files: test.txt
          name: Julien
          email: jul.charton@gmail.com 